### ISSUE TITLE
Volume bar overflow

### ISSUE THREAD

**Issue by Mennaruuk** [bocchilorenzo/invuedious#7]
![image](https://user-images.githubusercontent.com/52135169/106369505-1eb1bc80-6320-11eb-97fc-958ab6dc5c95.png)

I've seen this issue reported at Plyr's tracker. [The fix seems to be to update to the latest CSS](https://github.com/sampotts/plyr/issues/2026#issuecomment-731446123).

**Comment by bocchilorenzo** [comment]
Temporarily fixed by manually changing the css as mentioned [here](https://github.com/redxtech/vue-plyr/issues/308). Hopefully the library will be updated.

**Comment by Mennaruuk** [comment]
Thanks a lot @bocchilorenzo
